# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [4]:
import numpy as np




### 2. Print the NUMPY version and the configuration.


In [5]:
print(np.version.version)


1.26.4


### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [6]:
a = np.random.rand(2, 3, 5)


### 4. Print a.


In [7]:
print(a)


[[[0.25455456 0.01944785 0.46933005 0.98405308 0.22173807]
  [0.81561647 0.46470771 0.28335888 0.53730474 0.19958544]
  [0.58286077 0.40627982 0.62600863 0.84141115 0.40826488]]

 [[0.35521118 0.16081971 0.5041824  0.4839147  0.74919931]
  [0.0821174  0.10041258 0.05330367 0.56462228 0.42384608]
  [0.06018404 0.92288471 0.39441906 0.89102323 0.79228919]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [8]:
b = np.ones((2, 3, 5))



### 6. Print b.


In [9]:
print(b)


[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [11]:
size_a = a.size
size_b = b.size

are_same_size = size_a == size_b

print("Do a and b have the same size?", are_same_size)


Do a and b have the same size? True



### 8. Are you able to add a and b? Why or why not?


In [15]:
#Arrays cannot be added because they do not have the same shape.



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [16]:
b = np.ones((5, 2, 3))

c = np.transpose(b, (1, 2, 0))

print("Shape of c:", c.shape)
print("Transposed array c:\n", c)


Shape of c: (2, 3, 5)
Transposed array c:
 [[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [17]:
d = a + c

print("Shape of d:", d.shape)
print("Array d (result of a + c):\n", d)


Shape of d: (2, 3, 5)
Array d (result of a + c):
 [[[1.25455456 1.01944785 1.46933005 1.98405308 1.22173807]
  [1.81561647 1.46470771 1.28335888 1.53730474 1.19958544]
  [1.58286077 1.40627982 1.62600863 1.84141115 1.40826488]]

 [[1.35521118 1.16081971 1.5041824  1.4839147  1.74919931]
  [1.0821174  1.10041258 1.05330367 1.56462228 1.42384608]
  [1.06018404 1.92288471 1.39441906 1.89102323 1.79228919]]]



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [ ]:
print("Array a:\n", a)
print("\nArray d (a + c):\n", d)

# Each element in 'a' has been increased by 1 in 'd'.

Array a:
 [[[0.25455456 0.01944785 0.46933005 0.98405308 0.22173807]
  [0.81561647 0.46470771 0.28335888 0.53730474 0.19958544]
  [0.58286077 0.40627982 0.62600863 0.84141115 0.40826488]]

 [[0.35521118 0.16081971 0.5041824  0.4839147  0.74919931]
  [0.0821174  0.10041258 0.05330367 0.56462228 0.42384608]
  [0.06018404 0.92288471 0.39441906 0.89102323 0.79228919]]]

Array d (a + c):
 [[[1.25455456 1.01944785 1.46933005 1.98405308 1.22173807]
  [1.81561647 1.46470771 1.28335888 1.53730474 1.19958544]
  [1.58286077 1.40627982 1.62600863 1.84141115 1.40826488]]

 [[1.35521118 1.16081971 1.5041824  1.4839147  1.74919931]
  [1.0821174  1.10041258 1.05330367 1.56462228 1.42384608]
  [1.06018404 1.92288471 1.39441906 1.89102323 1.79228919]]]



### 12. Multiply a and c. Assign the result to e.


In [20]:
e = a * c




### 13. Does e equal to a? Why or why not?


In [ ]:
# Yes, e is equal to a because each element in 'a' has been multiplied by 1 in 'c', leaving the elements in 'a' unchanged.





### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [23]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)


### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [25]:
f = np.empty(d.shape)

print("Shape of f:", f.shape)


Shape of f: (2, 3, 5)





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [27]:
#...






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [35]:
### [your code here]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [36]:
### [your code here]